const STANDARD_TRACK_KEYS = ['id','title','genre','release_date','duration_seconds','youtube_url','sha256','sealed_date','attestation','license','licensing_contact'];
const MANIFEST_KEYS = ['title','filename','sha256','signature','publicKeyId','date'];
export function validateCatalog(catalog) { if(!catalog||typeof catalog!=='object'||Array.isArray(catalog)||!Array.isArray(catalog.tracks)) throw new Error('The music catalog is unavailable or malformed.'); const ids=new Set(); for(const track of catalog.tracks){ if(!track||typeof track!=='object'||JSON.stringify(Object.keys(track))!==JSON.stringify(STANDARD_TRACK_KEYS)) throw new Error('The music catalog contains a malformed track.'); if(!/^zs-\d{3}$/.test(track.id)||ids.has(track.id)||typeof track.title!=='string'||!track.title.trim()) throw new Error('The music catalog contains an invalid track identity.'); if(!Array.isArray(track.genre)||!/^[0-9a-f]{64}$/.test(track.sha256)||Number.isNaN(Date.parse(track.sealed_date))) throw new Error('The music catalog contains invalid verification data.'); ids.add(track.id); } return catalog; }
export function validateManifest(manifest) { if(!Array.isArray(manifest)) throw new Error('The signed manifest is unavailable or malformed.'); for(const entry of manifest){ if(!entry||typeof entry!=='object'||JSON.stringify(Object.keys(entry))!==JSON.stringify(MANIFEST_KEYS)) throw new Error('The signed manifest contains a malformed entry.'); } return manifest; }
export function buildTrackViews(catalog,manifest) { validateCatalog(catalog); validateManifest(manifest); return [...catalog.tracks].sort((a,b)=>Number(b.id.slice(3))-Number(a.id.slice(3))).map(track=>({...track,evidence:manifest.find(entry=>entry.title===track.title&&entry.sha256===track.sha256&&entry.date===track.sealed_date)??null})); }
export function filterTracks(tracks,query) { const needle=String(query??'').trim().toLocaleLowerCase(); if(!needle) return tracks; return tracks.filter(track=>[track.title,track.id,...(track.genre??[])].join(' ').toLocaleLowerCase().includes(needle)); }
export function formatSealDate(value) { const date=new Date(value); if(Number.isNaN(date.getTime())) return 'Recorded date unavailable'; return new Intl.DateTimeFormat('en-US',{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'}).format(date); }
export function safeRawPath(path) { if(!/^(?:catalog\.json|catalog-selections\.json|manifest\/(?:manifest|public-key)\.json)$/.test(path)) throw new Error('Unsafe evidence path.'); return path; }
async function loadJson(path) { const response=await fetch(path,{cache:'no-store'}); if(!response.ok) throw new Error(`Could not load ${path} (${response.status}).`); return response.json(); }
function element(tag,text,className) { const node=document.createElement(tag); if(text!==undefined) node.textContent=text; if(className) node.className=className; return node; }
function proofRow(list,label,value,className='') { list.append(element('dt',label),element('dd',value||'Unavailable',className||(!value?'missing':''))); }
function trackCard(track) { const article=element('article',undefined,'track'); const head=element('div',undefined,'track-head'); head.append(element('h3',track.title),element('span',track.id,'track-id')); const meta=element('p',undefined,'meta'); meta.append(element('span','Cryptographically sealed','verified'),element('span',`Seal recorded ${formatSealDate(track.sealed_date)}`),element('span',track.genre.join(' · '))); const details=element('details'); details.append(element('summary','View cryptographic proof')); const list=element('dl'); proofRow(list,'SHA-256',track.sha256,'proof-value'); proofRow(list,'Signature',track.evidence?.signature,'proof-value'); proofRow(list,'Public key ID',track.evidence?.publicKeyId,'proof-value'); proofRow(list,'Manifest title',track.evidence?.title); proofRow(list,'Recorded date',track.evidence?.date,'proof-value'); details.append(list); article.append(head,meta,details); return article; }
async function start() { const search=document.getElementById('track-search'),list=document.getElementById('track-list'),status=document.getElementById('catalog-status'),noResults=document.getElementById('no-results'),count=document.getElementById('result-count'),key=document.getElementById('public-key'); try { const [catalog,manifest,publicKey]=await Promise.all([loadJson(safeRawPath('catalog.json')),loadJson(safeRawPath('manifest/manifest.json')),loadJson(safeRawPath('manifest/public-key.json'))]); const tracks=buildTrackViews(catalog,manifest); key.textContent=JSON.stringify(publicKey,null,2); const render=()=>{ const visible=filterTracks(tracks,search.value); list.replaceChildren(...visible.map(trackCard)); count.textContent=`${visible.length} of ${tracks.length} sealed tracks`; noResults.hidden=visible.length!==0; }; status.hidden=true; search.disabled=false; search.addEventListener('input',render); render(); } catch(error) { status.textContent=`We could not load the sealed music catalog. ${error.message}`; status.classList.add('error'); count.textContent=''; key.textContent='Public key unavailable.'; } }
if(typeof document!=='undefined') start();
