import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { buildTrackViews,filterTracks,formatSealDate,safeRawPath,validateCatalog,validateManifest } from '../site.mjs';
const catalog=JSON.parse(readFileSync(new URL('../catalog.json',import.meta.url))); const manifest=JSON.parse(readFileSync(new URL('../manifest/manifest.json',import.meta.url))); const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
test('catalog and manifest build one newest-first view per catalog track',()=>{ const tracks=buildTrackViews(catalog,manifest); assert.equal(tracks.length,catalog.tracks.length); assert.equal(new Set(tracks.map(t=>t.id)).size,tracks.length); assert.deepEqual(tracks.map(t=>t.id),catalog.tracks.map(t=>t.id).sort((a,b)=>Number(b.slice(3))-Number(a.slice(3)))); assert.ok(tracks.every(t=>t.evidence)); assert.equal(tracks.filter(t=>t.title==='Ina Mi Chest').length,1); assert.equal(tracks.some(t=>t.title==='Ina Mi '),false); });
test('search matches title, id and genre without case sensitivity',()=>{ const tracks=buildTrackViews(catalog,manifest); assert.deepEqual(filterTracks(tracks,'INA MI CHEST').map(t=>t.id),['zs-070']); assert.deepEqual(filterTracks(tracks,'zs-064').map(t=>t.title),['Old Soul']); assert.equal(filterTracks(tracks,'reggae').length,tracks.length); assert.equal(filterTracks(tracks,'nothing will match this').length,0); assert.equal(filterTracks(tracks,'').length,tracks.length); });
test('malformed data and unsafe evidence links fail safely',()=>{ assert.throws(()=>validateCatalog([]),/unavailable or malformed/); assert.throws(()=>validateCatalog({tracks:[{id:'bad'}]}),/malformed track/); assert.throws(()=>validateManifest({}),/unavailable or malformed/); assert.throws(()=>validateManifest([{title:'<img onerror=alert(1)>'}]),/malformed entry/); assert.equal(safeRawPath('manifest/public-key.json'),'manifest/public-key.json'); assert.throws(()=>safeRawPath('javascript:alert(1)'),/Unsafe/); assert.equal(formatSealDate('bad'),'Recorded date unavailable'); });
test('page keeps evidence collapsed and exposes accessible states and raw files',()=>{ assert.match(html,/<label for="track-search">Search songs<\/label>/); assert.match(html,/aria-live="polite"/); assert.match(html,/<details id="public-key-details">/); assert.doesNotMatch(html,/<details id="public-key-details" open>/); assert.match(html,/No sealed tracks match that search/); assert.match(html,/Signed manifest JSON/); assert.match(html,/overflow-x: hidden/); assert.match(html,/overflow-wrap:anywhere/); });
